"""
Y-data profiling automates the EDA process and provides a comprehensive report on the dataset, 
including statistics, visualizations, and insights. 
It helps identify data quality issues, understand distributions, 
and detect correlations between variables.
It will provide HTML report which can be easily shared and viewed in a web browser.

So,install the required libraries
then
python -m pip install setuptools

"""


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport
df = pd.read_csv('titanic_data_updated.csv')
profile = ProfileReport(df ,title='Titanic Profile Report')

profile.to_file('my_report.html')


#As I am using python 3.13 so Ydata profiling is not compatible with it.
"""
So using Colab, i have uploaded the HTML file generated by Ydata profiling
"""