import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import  StandardScaler


from sklearn.datasets import make_moons
from sklearn.cluster import DBSCAN
from sklearn.cluster import KMeans

X,y=make_moons(n_samples=300,random_state=42,noise=0.06)
"""
X,y are the features and labels of the dataset respectively. 
The make_moons function generates a two-dimensional dataset with a 
moon-shaped distribution, which is often used for clustering and 
classification tasks. In this case, we are generating 300 samples with 
some added noise to make the clustering task more challenging.
"""
# Data Generation

"""
plt.scatter(X[:,0] , X[:,1])
plt.title('Original Moons Dataset')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.show()
"""


#Feature Scaling
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)
"""
plt.scatter(X_scaled[:,0] , X_scaled[:,1])
plt.title('Scaled Moons Dataset')
plt.xlabel('Feature 1 (Standardized)')
plt.ylabel('Feature 2 (Standardized)')
plt.show()
"""

#Density-Based Spatial Clustering (DBSCAN)
dbscan = DBSCAN(eps = 0.3 , min_samples =3 )
dbscan.fit(X_scaled)
label_dbscan= dbscan.labels_
#label_dbscan= dbscan.labels_ means that we are assigning the cluster labels generated by the DBSCAN algorithm to the variable label_dbscan. The dbscan.labels_ attribute contains the cluster labels for each data point in the dataset after fitting the DBSCAN model. Each unique label corresponds to a different cluster, and noise points are typically assigned a label of -1.

sns.scatterplot(x = X_scaled[: ,0] , y =X_scaled[: ,1] , hue = label_dbscan ,palette = 'viridis' )
plt.title('DBSCAN Clustering Results')
plt.xlabel('Feature 1 (Scaled)')
plt.ylabel('Feature 2 (Scaled)')
plt.legend(title='Cluster')
plt.show()